version: '3.8'
services:
  mongodb:
    image:  "mongo"
    volumes:
      - data:/data/db
    env_file:
      - ./server/config.env
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data/redis
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/config.env
    depends_on:
      - mongodb
      - redis
  client:
    build:
      context: ./client
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty:  true
volumes:
  data:
  redis: